name: Windows vcpkg CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Dependencies
      shell: bash
      run: |
        # Use a tag for reproducibility 
        git clone -b 2019.10 https://github.com/microsoft/vcpkg C:/vcpkg-gha
        C:/vcpkg-gha/bootstrap-vcpkg.sh
        C:/vcpkg-gha/vcpkg.exe install --triplet x64-windows protobuf boost-regex boost-system boost-thread
        
    - name: Configure, Compile and Install
      shell: bash
      run: |
        mkdir -p build
        cd build
        cmake -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg-gha/scripts/buildsystems/vcpkg.cmake \ 
              -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/install ..
        cmake --build . --config Debug --target INSTALL
        cmake --build . --config Release --target INSTALL
      
